import Box from "components/Layout/Box";
import Footer from "components/organisms/Footer";
import Header from "components/organisms/Header";
import Head from "next/head";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Header />
      <Box paddingX="px-32px">
        <main>{children}</main>
      </Box>
      <Footer />
    </>
  );
};

export default Layout;
