import Box from "components/Layout/Box";
import Footer from "components/organisms/Footer";
import type { NextPage } from "next";
import Head from "next/head";
import Text from "components/atoms/Text/input";
import LinkCardContainer from "components/containers/LinkCardContainer";
import Flex from "components/Layout/Flex";

const Home: NextPage = () => {
  return (
    <Box paddingX="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <Flex
          paddingY="py-16"
          flexDirection="flex-col"
          justifyContent="justify-center"
          alignItems="items-center"
        >
          <Text
            as="h1"
            margin="m-0"
            lineHeight="leading-normal"
            fontSize="text-7xl"
            textAlign="text-center"
          >
            Welcome to{" "}
            <a
              href="https://nextjs.org"
              className="no-underline text-blue-500 hover:underline"
            >
              Next.js!
            </a>
          </Text>
          <Text
            as="p"
            marginY="py-16"
            lineHeight="leading-normal"
            fontSize="text-2xl"
          >
            Get started by editing{" "}
            <Text
              as="code"
              fontSize={{ md: "text-base" }}
              padding="p-3"
              border="border-2"
              textColor="orange"
            >
              pages/index.tsx
            </Text>
          </Text>
          <LinkCardContainer />
        </Flex>
      </main>
      <Footer />
    </Box>
  );
};

export default Home;
